#!/usr/bin/env python3

# imports
import os, sys

# version
VERSION = "v1.4.1"

# run file
def runFile(f, w, c):
  # compile
  output = f.read().replace("func","def")
  output = output.replace("var ","")
  output = output.replace(" then",":")
  output = output.replace(";","\n")
  output = output.replace("/*", '"""')
  output = output.replace("*/", '"""')
  output = output.replace("end","")
  output = output.replace("true","True")
  output = output.replace("false","False")
  output = output.replace("//","#")
  output = output.replace("null","None")

  # create output file
  y = open(w, "x")
  y.write(output)
  y.close()
  
  if c == "-i":
    os.system(f"python3 {w}")
    os.system("")
  
  elif c == "-c":
    pass

if __name__ == "__main__":
  if len(sys.argv) == 1:
    print(VERSION)
  
  else:
    with open(sys.argv[1], "rt") as f:
      file = sys.argv[1]
      file = file.split(".")
      runFile(f, file[0] + ".py")
